vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       realisation_img:
           uri_prefix: '%product_attachment%'
           upload_destination: '%kernel.project_dir%/public/%product_attachment%'
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
