<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfn4uAU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfn4uAU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLfn4uAU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLfn4uAU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLfn4uAU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lfn4uAU',
    'container.build_id' => '6962a83a',
    'container.build_time' => 1699954510,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfn4uAU');
